Controllers films users
valentin32k/java-filmorate pull request #4
Opened 2022-12-14 22:40 UTC by valentin32k

2022-12-15 17:33 UTC, Donald522 requested changes
Привет! 
С возвращением :)
Тут все в общем нормально, я бы только не бросал исклчение в getAll методах

2022-12-15 17:33 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            throw new NotFoundException();
Это не является ошибкой.
Надо просто вернуть пустой список, это корректная ситуация

2022-12-15 17:33 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (name == null || name.equals("")) {
Можешь добавить библиотеку StringUtils, там есть метод isBlank
https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/StringUtils.html#isBlank-java.lang.CharSequence-

2022-12-15 17:33 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +public class Film {
Я бы советовал использовать аннотацию Value
Она сгенерирует неизменяемый класс.
Чтобы проставлять идентификаторы можно использовать аннотацию With, она сгенерирует соответствующие методы, которые работают как неизменяемые сеттеры, возвращая новый объект с проставленным полем

2022-12-15 17:33 UTC, Donald522 commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +    private HttpResponse<String> sendRequest(Film film, String method) {
Приватные методы обычно располагают ниже других
Здесь интерес представляют тесты, хочется сразу их видеть

2022-12-15 17:33 UTC, Donald522 commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +            if (method.equals("POST")) {
Хорошим тонон сравнения строки с константой является такая запись:
`"POST".equals(method)`
Она убереж от nullpointerexcpetion

2022-12-15 17:33 UTC, Donald522 commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +    void addValidFilm() {
Этот тест никак не проверяет то, что фильм создался в приложении
В классе контроллере можно удалить все, кроме return, и тест это не заметит

2022-12-15 17:33 UTC, Donald522 commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +    public static final String BIG_FILM_DESCRIPTION =
Стихов для моделирования длинной строки я еще не видел :)
Вообще в том же StringUtils есть метод repeat, который позволяет делать строки любой длины

2022-12-15 17:33 UTC, Donald522 commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> +        Assertions.assertEquals(404, response.statusCode());
А тут почему 404?
Либо тут название теста неверное

2022-12-15 21:21 UTC, valentin32k commented
Привет!
Все поправил, спасибо за ревью!

2022-12-15 21:29 UTC, valentin32k commented
Привет! Все поправил, спасибо за ревью!

2022-12-16 18:48 UTC, Donald522 approved these changes
Привет!
Все отлично сейчас

2022-12-16 18:48 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/controller/NotFoundException.java
> +@ResponseStatus(HttpStatus.NOT_FOUND)
Не увидел тестов на этот сценарий

2022-12-18 16:07 UTC, merged