10 Спринт (feat: Добавлены лайки)
valentin32k/java-filmorate pull request #5
Opened 2023-01-02 18:20 UTC by valentin32k

2023-01-04 21:24 UTC, Donald522 requested changes
Привет!

Так все хорошо, только не понял, почему тесты удалил. Хорошие же были. Надо было только добавить на новый функционал.
А так по мелочи оставил комментариев.

2023-01-04 21:24 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +            return null;
Я бы тут лучше 0 возвращал, получать null на запрос кол-ва - не очень ожидаемое поведение.
А полю likedUserIds можно вообще сделать значение по умолчанию пустой set, и проверять на null будет не нужно

2023-01-04 21:24 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +//        Вот здесь у меня небольшой вопрос как правильно делать.
Здесь можно и удалить.
В любом случае, когда мы потом будем хранить все в БД, то такие in-memory изменения работать не будут и обновлять придется явным образом.

2023-01-04 21:24 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (filmStorage.getFilmById(id) != null) {
Тут получается, что независимо от того, был элемент у нас или нет, мы наружу ответим 200
Не очень хорошо. Лучше явно отвечать 404, если мы не нашли элемент и не удалили его

2023-01-04 21:24 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        Comparator<Film> filmComparator = Comparator
Компаратор лучше вынести в private final static поле.
Если получение самых популярных фильмов будет частой операцией (что логично для сервисов типа кинопоиска), то это лишняя нагрузка на GC - будет создаваться куча одноразовых объектов компаратора (ведь все локальные переменные метода становятся мусором после завершения работы метода) .

2023-01-04 21:24 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (filmStorage.getFilmById(id) == null) {
Тут можно обойтись одним вызовом репозитория.
Всегда держи в голове, что вызов репозитория - это сетевая операция (это значит долгая и ненадежная, сеть может обрываться)

2023-01-04 21:24 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        User firstFriend = getUserById(id);
Здесь тоже лишние вызовы get можно не делать. Сразу клади в локальную переменную и эту переменную проверяй на null

2023-01-04 21:24 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +            userFriendsIds = new HashSet<>();
Можно добавить значение по умолчанию в класс User, этот метод попроще станет

2023-01-04 21:24 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public void removeUser(int id) {
То же замечание, что и с удалением фильма

2023-01-04 21:24 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                .limit(count)
Лучше этот лимит сделать параметром метода репозитория и делать сортировку и лимитирование там.
Сейчас это не так важно, но будет важно когда будет БД, а не in-memory хранилище. Зато переделывать метод сервиса уже не надо будет)

Фильмов может быть очень много и нет нужды вытягивать в память приложения всю базу, что взять 10 из них.

2023-01-06 16:35 UTC, valentin32k commented
Исправил замечания

2023-01-06 20:02 UTC, Donald522 approved these changes
Привет!

Сейчас все хорошо выглядит

2023-01-06 20:02 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    Set<Integer> likedUsersIds;
Насчет дефолтного значения - нельзя разве тут написать так?
`Set<Integer> likedUsersIds = new HashSet<>();`

2023-01-07 12:49 UTC, merged